server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: bankcards


jwt:
  secret: secret_bankcards_token
  expiration: 3600000
  issuer: bankcards

---

#Develop profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_database
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---

#Production profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://db:5432/bankcards_database
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true