server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcars_database
    username: postgres
    password: 1111
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your_super_secret_key_for_jwt_token_signing
  expiration: 3600000
  issuer: your-app-name

